<?php
use App\Models\CompanyService;use App\Models\Media;use App\Models\Project;use App\Models\Setting;use App\Models\Testimonial;
$name=(string)($company?->getAttribute('trade_name')?:config('app.name','Votre artisan'));$phone=(string)($company?->getAttribute('phone')??'');$phoneHref=preg_replace('/\D+/','',$phone);
$hero=$company?->getAttribute('hero_media_id')?Media::find((int)$company->getAttribute('hero_media_id'))?->getAttribute('url'):null;
$services=array_values(array_filter(CompanyService::all('sort_order ASC'),static fn($service)=>(bool)$service->getAttribute('is_active')));$projects=array_slice(Project::visible(),0,6);$reviews=array_slice(Testimonial::visible(),0,3);
$defaults=['hero_eyebrow'=>'Artisan local','hero_title'=>'Votre projet entre de bonnes mains.','services_eyebrow'=>'Nos prestations','services_title'=>'Des services adaptés à vos besoins','about_eyebrow'=>'Qui sommes-nous','about_title'=>'Un savoir-faire de proximité','zone_eyebrow'=>'Zone d’intervention','zone_title'=>'Nous intervenons près de chez vous','zone_text'=>'Contactez-nous pour vérifier notre disponibilité dans votre commune.','zone_cities'=>'','projects_eyebrow'=>'Nos réalisations','projects_title'=>'Des chantiers menés avec soin','reviews_eyebrow'=>'Avis clients','reviews_title'=>'La satisfaction de nos clients','sav_eyebrow'=>'Intervention rapide','sav_title'=>'Un interlocuteur disponible pour vos urgences','sav_text'=>'Notre équipe reste disponible pour sécuriser votre bâtiment et organiser rapidement l’intervention adaptée.','sav_point_1'=>'Une réponse claire et rapide','sav_point_2'=>'Un devis gratuit et transparent','sav_point_3'=>'Un chantier propre et sécurisé','blog_eyebrow'=>'Conseils & expertise','blog_title'=>'Nos derniers articles'];
$copy=array_merge($defaults,json_decode((string)(Setting::first(['key'=>'content.home_copy'])?->getAttribute('value')??'{}'),true)?:[]);$mediaUrl=static fn($id)=>$id?Media::find((int)$id)?->getAttribute('url'):null;
$savId=(int)(Setting::first(['key'=>'content.home_sav_media_id'])?->getAttribute('value')??0);$savImage=$mediaUrl($savId)?:$hero;$postImage=static fn(array $post):?string=>is_string($post['_embedded']['wp:featuredmedia'][0]['source_url']??null)?$post['_embedded']['wp:featuredmedia'][0]['source_url']:null;
?>
<main class="professional-home editorial-home">
<div class="ph-hero-wrap"><section class="ph-hero<?= $hero?'':' ph-hero-fallback' ?>"><?php if($hero): ?><img src="<?= e($hero) ?>" alt="<?= e($name) ?>" fetchpriority="high"><?php endif; ?><div class="ph-overlay"></div><div class="ph-hero-copy"><span class="ph-eyebrow"><?= e($copy['hero_eyebrow']) ?><?= $company?->getAttribute('city')?' · '.e($company->getAttribute('city')):'' ?></span><h1><?= e($page->getAttribute('h1')?:$copy['hero_title']) ?></h1><?php if($company?->getAttribute('short_description')): ?><p><?= e($company->getAttribute('short_description')) ?></p><?php endif; ?><div><a class="ph-btn yellow" href="#devis">Demander un devis gratuit</a><?php if($phone!==''): ?><a class="ph-btn white" href="tel:<?= e($phoneHref) ?>">Appeler — <?= e($phone) ?></a><?php endif; ?></div></div></section></div>
<?php if($services): ?><section class="ph-section editorial-section" id="services"><span class="ph-eyebrow blue"><?= e($copy['services_eyebrow']) ?></span><div class="editorial-heading"><h2><?= e($copy['services_title']) ?></h2></div><div class="marketing-service-grid"><?php foreach(array_slice($services,0,6) as $service):$image=$mediaUrl($service->getAttribute('image_media_id')); ?><a class="marketing-service-card" href="/<?= e($service->getAttribute('slug')) ?>"><?php if($image): ?><img src="<?= e($image) ?>" alt="<?= e($service->getAttribute('public_name')) ?>" loading="lazy"><?php else: ?><div class="marketing-image-empty" aria-hidden="true"><?= e(mb_strtoupper(mb_substr((string)$service->getAttribute('public_name'),0,1))) ?></div><?php endif; ?><div><h3><?= e($service->getAttribute('public_name')) ?></h3><p><?= e($service->getAttribute('description')) ?></p><span>Découvrir le service →</span></div></a><?php endforeach; ?></div></section><?php endif; ?>
<section class="editorial-about"><div><span class="ph-eyebrow blue"><?= e($copy['about_eyebrow']) ?></span><h2><?= e($copy['about_title']) ?></h2><?php if($company?->getAttribute('long_description')): ?><p><?= nl2br(e($company->getAttribute('long_description'))) ?></p><?php elseif($company?->getAttribute('short_description')): ?><p><?= e($company->getAttribute('short_description')) ?></p><?php endif; ?><a class="outline-link" href="/a-propos">Découvrir l’entreprise →</a></div><?php if($hero): ?><img src="<?= e($hero) ?>" alt="<?= e($name) ?> en intervention" loading="lazy"><?php endif; ?></section>
<section class="editorial-emergency"><div><span class="ph-eyebrow blue"><?= e($copy['sav_eyebrow']) ?></span><h2><?= e($copy['sav_title']) ?></h2><p><?= e($copy['sav_text']) ?></p><ul><li><?= e($copy['sav_point_1']) ?></li><li><?= e($copy['sav_point_2']) ?></li><li><?= e($copy['sav_point_3']) ?></li></ul><div><?php if($phone!==''): ?><a class="ph-btn yellow" href="tel:<?= e($phoneHref) ?>">Appeler — <?= e($phone) ?></a><?php endif; ?><a class="ph-btn outline" href="#devis">Contacter notre équipe</a></div></div><?php if($savImage): ?><img src="<?= e($savImage) ?>" alt="Intervention de <?= e($name) ?>" loading="lazy"><?php endif; ?></section>
<?php if($projects): ?><section class="ph-section editorial-section projects-editorial"><span class="ph-eyebrow blue"><?= e($copy['projects_eyebrow']) ?></span><div class="editorial-heading"><h2><?= e($copy['projects_title']) ?></h2><a href="/realisations">Toutes les réalisations →</a></div><div class="marketing-project-grid"><?php foreach($projects as $project):$image=$mediaUrl($project->getAttribute('after_media_id'))?:$mediaUrl($project->getAttribute('before_media_id'));if(!$image)continue; ?><figure><div class="project-photo"><img src="<?= e($image) ?>" alt="<?= e($project->getAttribute('alt_text')?:$project->getAttribute('title')) ?>" loading="lazy"><span>▧ Photos</span></div><figcaption><strong><?= e($project->getAttribute('title')) ?></strong><small>Chantier réalisé avec soin</small></figcaption></figure><?php endforeach; ?></div></section><?php endif; ?>
<?= view('public.partials.zone_editorial',['company'=>$company,'copy'=>$copy]) ?>
<?php if($reviews): ?><section class="ph-section editorial-section reviews-editorial"><span class="ph-eyebrow blue"><?= e($copy['reviews_eyebrow']) ?></span><div class="editorial-heading"><h2><?= e($copy['reviews_title']) ?></h2><a href="/avis-clients">Tous les avis →</a></div><div class="marketing-review-grid"><?php foreach($reviews as $review): ?><article><div class="stars"><?= str_repeat('★',max(1,(int)$review->getAttribute('rating'))) ?></div><p>“<?= e($review->getAttribute('content')) ?>”</p><strong><?= e($review->getAttribute('author_name')) ?></strong></article><?php endforeach; ?></div></section><?php endif; ?>
<?php if(!empty($latestBlogPosts)): ?><section class="ph-section editorial-section blog-editorial"><span class="ph-eyebrow blue"><?= e($copy['blog_eyebrow']) ?></span><div class="editorial-heading"><h2><?= e($copy['blog_title']) ?></h2><a href="/blog">Voir tous les articles →</a></div><div class="editorial-blog-grid"><?php foreach($latestBlogPosts as $post):$image=$postImage($post);$title=trim(strip_tags(html_entity_decode($post['title']['rendered']??'',ENT_QUOTES|ENT_HTML5,'UTF-8')));$excerpt=trim(strip_tags(html_entity_decode($post['excerpt']['rendered']??'',ENT_QUOTES|ENT_HTML5,'UTF-8'))); ?><a href="/blog/<?= e($post['slug']??'') ?>"><?php if($image): ?><img src="<?= e($image) ?>" alt="<?= e($title) ?>" loading="lazy"><?php else: ?><div class="blog-image-fallback">Conseils</div><?php endif; ?><div><small><?= e(isset($post['date'])?date('d/m/Y',strtotime((string)$post['date'])):'') ?></small><h3><?= e($title) ?></h3><p><?= e(mb_strimwidth($excerpt,0,155,'…')) ?></p><span>Lire l’article →</span></div></a><?php endforeach; ?></div></section><?php endif; ?>
<?= view('public.partials.quote_card',['company'=>$company]) ?>
</main>
