<?php
/** @var array<int,\App\Models\Testimonial> $reviews */
$name=(string)($company?->getAttribute('trade_name')?:config('app.name','Votre artisan'));
$phone=(string)($company?->getAttribute('phone')??'');
?>
<main class="reviews-page">
  <section class="reviews-hero"><div class="reviews-hero-inner"><span class="reviews-eyebrow">L’expérience <?= e($name) ?></span><h1>La confiance de nos clients,<br>notre meilleure référence.</h1><p>Installation, entretien ou dépannage : découvrez les retours de celles et ceux qui nous ont confié leur confort.</p><?php if($average!==null): ?><div class="reviews-score"><div><span><?= number_format((float)$average,1,',','') ?></span><small>/ 5</small></div><div><strong><?= str_repeat('★',5) ?></strong><p>Note globale calculée sur <?= (int)$reviewCount ?> avis client<?= $reviewCount>1?'s':'' ?></p></div></div><?php endif; ?></div></section>

  <section class="reviews-list"><div class="reviews-list-inner"><span class="reviews-eyebrow blue">Tous les témoignages</span><h2>Ce que nos clients disent de nous</h2><?php if($reviews): ?><div class="reviews-all-grid"><?php foreach($reviews as $review): ?><article><div class="reviews-stars"><?= str_repeat('★',max(1,(int)$review->getAttribute('rating'))) ?></div><blockquote>« <?= e($review->getAttribute('content')) ?> »</blockquote><div><strong><?= e($review->getAttribute('author_name')) ?></strong><?php if($review->getAttribute('author_city')): ?><span><?= e($review->getAttribute('author_city')) ?></span><?php endif; ?><small><?= e($review->getAttribute('role_or_service')?:($review->getAttribute('source')==='google'?'Avis Google':'Client')) ?></small></div></article><?php endforeach; ?></div><?php else: ?><p>Aucun avis n’est encore publié.</p><?php endif; ?></div></section>

  <section class="reviews-sav"><div class="reviews-sav-inner"><div><span class="reviews-eyebrow">Notre engagement</span><h2>Le suivi client continue après l’installation</h2><p>Un chantier réussi ne s’arrête pas à la mise en service. Notre équipe reste disponible pour vos questions, l’entretien de vos équipements et les interventions de service après-vente.</p></div><div class="sav-points"><article><b>01</b><h3>Mise en service</h3><p>Explications claires et réglages adaptés à votre logement.</p></article><article><b>02</b><h3>Suivi personnalisé</h3><p>Une équipe disponible pour répondre à vos questions après les travaux.</p></article><article><b>03</b><h3>Entretien & SAV</h3><p>Maintenance et dépannage pour préserver les performances de votre installation.</p></article></div><?php if($phone): ?><a href="tel:<?= e(preg_replace('/\D+/','',$phone)) ?>">Besoin de notre SAV ? Appelez le <?= e($phone) ?></a><?php else: ?><a href="/contact">Contacter notre service après-vente</a><?php endif; ?></div></section>
</main>
