<?php
/** @var array<int,array<string,mixed>> $services @var array<string,string> $groups @var array<int,string> $serviceGroups @var array<string,\App\Models\Media> $groupImages */
$success=flash_message('success');$errors=flash_errors();$grouped=[];$unclassified=[];
foreach($services as $service){$slug=$serviceGroups[(int)$service['id']]??'';if($slug!==''&&isset($groups[$slug]))$grouped[$slug][]=$service;else$unclassified[]=$service;}
?>
<div class="admin-topbar"><div><h1>Groupes &amp; sous-services</h1><p style="color:var(--muted);margin:7px 0 0">Ouvrez un groupe pour gérer ses prestations ou en créer une nouvelle.</p></div><a class="btn" href="/admin/services/create">Ajouter un service</a></div>
<?php if($success): ?><div class="alert ok"><?= e($success) ?></div><?php endif; ?><?php if(!empty($errors['form'])): ?><div class="alert error"><?= e($errors['form']) ?></div><?php endif; ?>
<div class="service-admin-groups">
<?php foreach($groups as $slug=>$label):$children=$grouped[$slug]??[]; ?>
<details class="service-admin-group" <?= $slug==='climatisation'?'open':'' ?>><summary><span><b><?= e($label) ?></b><small><?= count($children) ?> sous-service<?= count($children)>1?'s':'' ?></small></span><i><?= count($children) ?></i></summary><div class="service-admin-group-body">
<div class="service-group-featured-admin"><?php if(!empty($groupImages[$slug])): ?><img src="<?= e($groupImages[$slug]->getAttribute('url')) ?>" alt="Photo <?= e($label) ?>"><?php else: ?><span>Aucune photo de groupe</span><?php endif; ?><form method="post" action="/admin/services/group-image" enctype="multipart/form-data"><?= csrf_field() ?><input type="hidden" name="group_slug" value="<?= e($slug) ?>"><label>Photo mise en avant du groupe sur l’accueil</label><input type="file" name="group_featured_image" accept="image/*" required><button type="submit" class="btn secondary sm">Enregistrer la photo</button></form></div>
<?php if($children): ?><div class="service-admin-list"><?php foreach($children as $service): ?><article><?php if(!empty($service['image_url'])): ?><img src="<?= e($service['image_url']) ?>" alt=""><?php else: ?><span class="service-admin-noimage">21°</span><?php endif; ?><div><strong><?= e($service['public_name']) ?></strong><small>/<?= e($service['slug']) ?></small><div class="service-admin-badges"><em class="badge <?= $service['is_active']?'published':'archived' ?>"><?= $service['is_active']?'Actif':'Inactif' ?></em><?php if($service['show_in_menu']): ?><em class="badge draft">Dans le menu</em><?php endif; ?></div></div><a class="btn secondary sm" href="/admin/services/<?= (int)$service['id'] ?>">Modifier</a></article><?php endforeach; ?></div><?php else: ?><p class="service-admin-empty">Aucun sous-service dans ce groupe.</p><?php endif; ?>
<details class="service-admin-add"><summary>＋ Ajouter un sous-service dans <?= e($label) ?></summary><form method="post" action="/admin/services"><?= csrf_field() ?><input type="hidden" name="service_group" value="<?= e($slug) ?>"><div class="row"><div><label>Nom du sous-service</label><input type="text" name="public_name" required placeholder="Ex. Entretien de <?= e(mb_strtolower($label)) ?>"></div><div><label>Description courte</label><input type="text" name="description" placeholder="Décrivez la prestation en une phrase"></div></div><button type="submit">Créer le sous-service</button></form></details>
</div></details><?php endforeach; ?>
<?php if($unclassified): ?><details class="service-admin-group"><summary><span><b>Services non classés</b><small>À rattacher à un groupe</small></span><i><?= count($unclassified) ?></i></summary><div class="service-admin-group-body"><div class="service-admin-list"><?php foreach($unclassified as $service): ?><article><?php if(!empty($service['image_url'])): ?><img src="<?= e($service['image_url']) ?>" alt=""><?php else: ?><span class="service-admin-noimage">21°</span><?php endif; ?><div><strong><?= e($service['public_name']) ?></strong><small>/<?= e($service['slug']) ?></small></div><a class="btn secondary sm" href="/admin/services/<?= (int)$service['id'] ?>">Choisir un groupe</a></article><?php endforeach; ?></div></div></details><?php endif; ?>
</div>
<style>.service-group-featured-admin{display:grid;grid-template-columns:220px 1fr;gap:20px;align-items:center;margin-bottom:18px;padding:16px;border-radius:14px;background:#f5f8fb}.service-group-featured-admin>img,.service-group-featured-admin>span{width:220px;height:125px;border-radius:11px;object-fit:cover}.service-group-featured-admin>span{display:grid;place-items:center;background:#e8edf3;color:var(--muted);font-size:12px}.service-group-featured-admin form{margin:0}.service-group-featured-admin input[type=file]{margin-bottom:10px}@media(max-width:650px){.service-group-featured-admin{grid-template-columns:1fr}.service-group-featured-admin>img,.service-group-featured-admin>span{width:100%;height:170px}}</style>
