<?php
use App\Models\Media;
use App\Models\Project;
use App\Models\Testimonial;
$projects=$projects??Project::visible();$faqs=$faqs??[];$partnerLogos=$partnerLogos??[];$currentService=$currentService??null;
$reviews=array_slice(Testimonial::visibleGoogle(),0,3);$mediaUrl=static fn($id)=>$id?Media::find((int)$id)?->getAttribute('url'):null;
$brandName=(string)($company?->getAttribute('trade_name')?:config('app.name','Votre artisan'));
?>
<?php if(!empty($relatedServices)): ?><section class="marketing-section related-services"><div class="marketing-head"><div><span class="eyebrow">Nos prestations</span><h2>Les services proposés</h2></div><p>Découvrez les interventions associées à votre projet.</p></div><div class="marketing-service-grid"><?php foreach($relatedServices as $service):$img=$mediaUrl($service->getAttribute('image_media_id')); ?><a href="/<?= e($service->getAttribute('slug')) ?>" class="marketing-service-card"><?php if($img): ?><img src="<?= e($img) ?>" alt="<?= e($service->getAttribute('public_name')) ?>" loading="lazy"><?php else: ?><div class="marketing-image-empty"><?= e($brandName) ?></div><?php endif; ?><div><h3><?= e($service->getAttribute('public_name')) ?></h3><p><?= e($service->getAttribute('description')) ?></p><span>En savoir plus →</span></div></a><?php endforeach; ?></div></section><?php endif; ?>

<?php if($projects): ?><section class="marketing-section projects-showcase"><div class="marketing-head"><div><span class="eyebrow">Réalisations</span><h2>Nos interventions récentes</h2></div></div><div class="marketing-project-grid"><?php foreach(array_slice($projects,0,6) as $project):$img=$mediaUrl($project->getAttribute('after_media_id'))?:$mediaUrl($project->getAttribute('before_media_id'));if(!$img)continue; ?><figure><img src="<?= e($img) ?>" alt="<?= e($project->getAttribute('alt_text')?:$project->getAttribute('title')) ?>" loading="lazy"><figcaption><strong><?= e($project->getAttribute('title')) ?></strong></figcaption></figure><?php endforeach; ?></div><a class="marketing-more" href="/realisations">Voir toutes les réalisations →</a></section><?php endif; ?>

<?php if($reviews): ?><section class="marketing-reviews"><div class="marketing-section"><div class="marketing-head"><div><span class="eyebrow">Avis clients</span><h2>Ils nous ont fait confiance</h2></div></div><div class="marketing-review-grid"><?php foreach($reviews as $review): ?><article><div class="stars"><?= str_repeat('★',max(1,(int)$review->getAttribute('rating'))) ?></div><p>“<?= e($review->getAttribute('content')) ?>”</p><strong><?= e($review->getAttribute('author_name')) ?></strong></article><?php endforeach; ?></div><a class="reviews-more-button" href="/avis-clients">Voir tous les avis →</a></div></section><?php endif; ?>

<?php if($partnerLogos): ?><section class="service-partners"><div class="marketing-section"><div class="marketing-head"><div><span class="eyebrow">Marques &amp; partenaires</span><h2>Nos partenaires</h2></div></div><div class="service-partner-grid"><?php foreach($partnerLogos as $logo): ?><span><img src="<?= e($logo->getAttribute('url')) ?>" alt="Logo partenaire" loading="lazy"></span><?php endforeach; ?></div></div></section><?php endif; ?>

<section class="service-faq"><div class="service-faq-inner"><div class="marketing-head"><div><span class="eyebrow">Questions fréquentes</span><h2>Tout savoir avant votre projet</h2></div></div><div class="service-faq-list"><?php if($faqs):foreach($faqs as $faq): ?><details><summary><?= e($faq->getAttribute('question')) ?></summary><p><?= e($faq->getAttribute('answer')) ?></p></details><?php endforeach;else:$serviceName=(string)($currentService?->getAttribute('public_name')?:'ce service'); ?><details><summary>Comment obtenir un devis pour <?= e(mb_strtolower($serviceName)) ?> ?</summary><p>Décrivez votre projet dans le formulaire. Notre équipe vous recontactera pour préciser votre besoin.</p></details><details><summary>Dans quelles villes intervenez-vous ?</summary><p>Consultez nos zones d’intervention ou contactez-nous pour vérifier votre commune.</p></details><?php endif; ?></div></div></section>
<?= view('public.partials.quote_card',['company'=>$company,'currentService'=>$currentService]) ?>
