<?php
use App\Models\Media;use App\Models\Setting;
$name=(string)($company?->getAttribute('trade_name')?:config('app.name','Votre artisan'));$agencyCity=(string)($company?->getAttribute('city')??'');$department=(string)($company?->getAttribute('department')??'');$region=(string)($company?->getAttribute('region')??'');$radius=(int)($company?->getAttribute('service_radius_km')??0);$copy=$copy??[];
$cities=array_values(array_filter(array_map('trim',preg_split('/[,;\n]/',(string)($copy['zone_cities']??''))?:[])));if(!$cities&&$agencyCity!=='')$cities[]=$agencyCity;
$zoneId=(int)(Setting::first(['key'=>'content.home_zone_media_id'])?->getAttribute('value')??0);$zoneImage=$zoneId?Media::find($zoneId)?->getAttribute('url'):null;
$zoneMap=(string)(json_decode((string)(Setting::first(['key'=>'visual.zone_map'])?->getAttribute('value')??''),true)?:'');
$zoneMap=preg_match('#^/assets/images/[a-z0-9/_-]+\.svg$#',$zoneMap)?$zoneMap:'/assets/images/jc-toitures/carte-val-doise.svg';
?>
<section class="zone-card editorial-zone"><div class="zone-card-inner"><div class="zone-card-copy"><span class="ph-eyebrow"><?= e($copy['zone_eyebrow']??'Zone d’intervention') ?></span><h2><?= e($copy['zone_title']??($name.' intervient chez vous')) ?></h2><p class="zone-card-text"><?= e($copy['zone_text']??'Contactez-nous pour vérifier notre disponibilité dans votre commune.') ?><?= $radius>0?' Nous nous déplaçons dans un rayon d’environ '.e($radius).' km.':'' ?></p><?php if($cities): ?><div class="zone-card-pills"><?php foreach($cities as $city): ?><span class="zone-pill"><?= e($city) ?></span><?php endforeach; ?></div><?php endif; ?><a class="zone-card-cta" href="#devis">Vérifier votre commune →</a></div><div class="zone-card-map" aria-label="Carte de la zone d’intervention<?= $department!==''?' : '.e($department):'' ?>"><img src="<?= e($zoneImage ?: $zoneMap) ?>" alt="Carte des zones d’intervention de <?= e($name) ?><?= $agencyCity!==''?' à '.e($agencyCity):'' ?><?= $department!==''?' et en '.e($department):'' ?>" loading="lazy"></div></div></section>
