<?php $errors=flash_errors();$success=flash_message(); ?>
<div class="card"><h1><?= e($pageTitle) ?></h1><p>Activez une prestation dans une ou plusieurs villes. Chaque combinaison produit une page unique, rédigée manuellement ou générée par l’IA.</p><?php if($success): ?><div class="alert success"><?= e($success) ?></div><?php endif; ?><?php if(!empty($errors['form'])): ?><div class="alert error"><?= e($errors['form']) ?></div><?php endif; ?></div>

<div class="card"><h2>Activer des combinaisons</h2><form method="post" action="/admin/local-pages"><?= csrf_field() ?><div class="row"><div><label>Service</label><select name="company_service_id" required><option value="">Choisir</option><?php foreach($services as $service): ?><option value="<?= (int)$service->id() ?>"><?= e($service->getAttribute('public_name')) ?></option><?php endforeach; ?></select></div><div><label>Mode de contenu</label><select name="content_mode"><option value="ai">Génération IA</option><option value="manual">Contenu manuel / JSON</option></select></div><div><label>Publication après génération</label><select name="status"><option value="draft">Brouillon</option><option value="published">Publier</option></select></div></div><label>Villes</label><div class="local-city-grid"><?php foreach($cities as $city): ?><label><input type="checkbox" name="city_ids[]" value="<?= (int)$city['id'] ?>"> <?= e($city['name']) ?> <small><?= e($city['postal_code']) ?></small></label><?php endforeach; ?></div><button type="submit">Activer les pages</button></form></div>

<div class="card"><h2>Import JSON en cascade</h2><p>Le service accepte son identifiant ou son slug. La ville accepte son identifiant, son code INSEE, son slug ou son nom. Seules les villes activées dans « Zones d’intervention » sont acceptées.</p><textarea id="local-json" rows="14" spellcheck="false">{
  "pages": [
    {
      "service": "nom-du-service",
      "city": "code-insee-ou-ville",
      "mode": "manual",
      "status": "draft",
      "content": {
        "title": "Titre de la page",
        "h1": "Service à Ville",
        "meta_title": "Titre SEO",
        "meta_description": "Description SEO",
        "introduction": "Introduction propre à cette ville.",
        "sections": [{"heading": "Titre de section", "content": "Contenu local utile."}],
        "faq": [{"question": "Question locale ?", "answer": "Réponse vérifiée."}],
        "cta_title": "Votre projet",
        "cta_text": "Contactez-nous."
      }
    }
  ]
}</textarea><div class="actions-bar"><button type="button" id="import-json">Importer le JSON</button><a class="btn secondary" href="/admin/local-pages/export.json" target="_blank">Exporter la configuration JSON</a><button type="button" class="secondary" id="generate-pending">Générer toutes les pages en attente</button></div><pre id="cascade-log" class="cascade-log" hidden></pre></div>

<div class="card"><h2>Pages configurées (<?= count($localPages) ?>)</h2><?php if(!$localPages): ?><p>Aucune combinaison activée.</p><?php endif; ?><div class="local-page-list"><?php foreach($localPages as $local):$payload=json_encode($local['content_payload']?json_decode((string)$local['content_payload'],true):[],JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES); ?><details class="local-page-row" data-local-id="<?= (int)$local['id'] ?>"><summary><span><strong><?= e($local['service_name']) ?> — <?= e($local['city_name']) ?></strong><small><?= e($local['postal_code']) ?> · <?= e($local['content_mode']) ?> · <?= e($local['generation_status']) ?> · <?= e($local['status']) ?></small></span><?php if($local['page_slug']): ?><a href="/<?= e($local['page_slug']) ?>" target="_blank" rel="noopener">Voir ↗</a><?php endif; ?></summary><form method="post" action="/admin/local-pages/<?= (int)$local['id'] ?>"><?= csrf_field() ?><div class="row"><label>Mode<select name="content_mode"><option value="ai" <?= $local['content_mode']==='ai'?'selected':'' ?>>IA</option><option value="manual" <?= $local['content_mode']==='manual'?'selected':'' ?>>Manuel / JSON</option></select></label><label>Statut<select name="status"><option value="draft" <?= $local['status']==='draft'?'selected':'' ?>>Brouillon</option><option value="published" <?= $local['status']==='published'?'selected':'' ?>>Publié</option></select></label><label class="checkbox-row"><input type="checkbox" name="is_active" value="1" <?= $local['is_active']?'checked':'' ?>> Active et indexable</label></div><label>Informations propres à cette ville (JSON)</label><textarea name="content_payload" rows="10"><?= e($payload?:'{}') ?></textarea><?php if($local['error_message']): ?><div class="alert error"><?= e($local['error_message']) ?></div><?php endif; ?><div class="actions-bar"><button type="submit">Enregistrer</button><button type="button" class="secondary generate-one" data-id="<?= (int)$local['id'] ?>">Générer maintenant</button></div></form></details><?php endforeach; ?></div></div>

<script>
(()=>{const csrf=<?= json_encode(csrf_token()) ?>,log=document.getElementById('cascade-log');const write=m=>{log.hidden=false;log.textContent+=m+'\n';};async function generate(id){const body=new URLSearchParams({_csrf_token:csrf});const response=await fetch('/admin/local-pages/'+id+'/generate',{method:'POST',headers:{Accept:'application/json','Content-Type':'application/x-www-form-urlencoded'},body});const result=await response.json();if(!response.ok)throw new Error(result.error||'Erreur');return result;}
document.querySelectorAll('.generate-one').forEach(button=>button.addEventListener('click',async()=>{button.disabled=true;try{const result=await generate(button.dataset.id);write('✓ Page '+result.id+' : '+result.url);}catch(error){write('✗ '+error.message);}finally{button.disabled=false;}}));
document.getElementById('generate-pending').addEventListener('click',async function(){this.disabled=true;const ids=[...document.querySelectorAll('[data-local-id]')].filter(row=>row.querySelector('summary small').textContent.includes('pending')||row.querySelector('summary small').textContent.includes('failed')).map(row=>row.dataset.localId);for(const id of ids){try{const result=await generate(id);write('✓ '+result.url);}catch(error){write('✗ Page '+id+' : '+error.message);}}this.disabled=false;});
document.getElementById('import-json').addEventListener('click',async function(){this.disabled=true;try{const body=new URLSearchParams({_csrf_token:csrf,payload:document.getElementById('local-json').value});const response=await fetch('/admin/local-pages/import-json',{method:'POST',headers:{Accept:'application/json','Content-Type':'application/x-www-form-urlencoded'},body});const result=await response.json();if(!response.ok)throw new Error(result.error||'Erreur');write('Import : '+result.created+' page(s).');(result.errors||[]).forEach(write);setTimeout(()=>location.reload(),700);}catch(error){write('✗ '+error.message);}finally{this.disabled=false;}});})();
</script>
<style>.local-city-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(210px,1fr));gap:8px;max-height:320px;overflow:auto;padding:12px;border:1px solid #d8dee6;border-radius:8px;margin-bottom:18px}.local-city-grid label{display:flex;gap:8px;align-items:center}.local-city-grid input{width:auto}.local-page-row{border:1px solid #d8dee6;border-radius:9px;padding:12px;margin-bottom:10px}.local-page-row summary{display:flex;justify-content:space-between;align-items:center;cursor:pointer}.local-page-row summary span,.local-page-row summary small{display:block}.cascade-log{padding:14px;background:#172033;color:#d6f5dd;border-radius:8px;white-space:pre-wrap}</style>
