CREATE TABLE IF NOT EXISTS pages (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    type ENUM('home', 'about', 'service', 'realizations', 'zones', 'faq', 'contact', 'legal_mentions', 'privacy', 'cookies', 'terms', 'local', 'custom') NOT NULL,
    company_service_id INT UNSIGNED NULL,
    slug VARCHAR(191) NOT NULL,
    title VARCHAR(255) NULL,
    h1 VARCHAR(255) NULL,
    meta_title VARCHAR(255) NULL,
    meta_description VARCHAR(500) NULL,
    canonical_url VARCHAR(500) NULL,
    og_media_id INT UNSIGNED NULL,
    schema_type VARCHAR(60) NULL,
    status ENUM('draft', 'published', 'archived') NOT NULL DEFAULT 'draft',
    indexable TINYINT(1) NOT NULL DEFAULT 1,
    quality_score TINYINT UNSIGNED NULL,
    content_is_placeholder TINYINT(1) NOT NULL DEFAULT 0,
    author_id INT UNSIGNED NULL,
    published_at DATETIME NULL,
    last_generated_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_pages_company_service FOREIGN KEY (company_service_id) REFERENCES company_services (id) ON DELETE SET NULL,
    CONSTRAINT fk_pages_og_media FOREIGN KEY (og_media_id) REFERENCES media (id) ON DELETE SET NULL,
    CONSTRAINT fk_pages_author FOREIGN KEY (author_id) REFERENCES users (id) ON DELETE SET NULL,
    UNIQUE KEY uniq_pages_slug (slug),
    INDEX idx_pages_type (type),
    INDEX idx_pages_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
